### ISSUE TITLE
Checklist for v0.0.2

### ISSUE THREAD

**Issue by alexcs-bsft** [blueshift-labs/ng-interop#1]
## Props:
- [x] Fix `Number` prop & attr passing
- [x] Fix optional `String` props just stringifying `null` and `undefined`, but still allow `''`
- [x] Fix required props where the value is falsy
